### ISSUE TITLE
Rhino or Nashorn

### ISSUE THREAD

**Issue by fredfortier** [medialize/sass.js#36]
I would like to include a SASS compiler in my Java app.

This seemed like a good idea since the JVM offers decent JavaScript engines.

I tried running the script using the latest version of Rhino. Basically, it gets hung up because web workers are not available in this context.

I tried running the sass.sync.js script.
Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot call method "slice" of null (file:/Users/fredfortier/Code/kwcn-post-13/kwcn-business-logic/src/test/resources/modules/sass/sass.sync.js#76)

Do you have any tips on how I could tweak things up to make them run in such context?

**Comment by rodneyrehm** [comment]
I know nothing about Rhino and Nashorn. Maybe [these guys](https://twitter.com/mrdrjennings/status/586581653688037377) are able to help you out?

**Comment by fredfortier** [comment]
Looking at their project, they are using this file: https://github.com/yogthos/lein-sass/blob/master/resources/sass.min.js. Is this a modified version of the script?

I understand that Rhino and Nashorn fully support ES5 but do not have browser api (no console, no document, no Worker). The lack of a Web Worker specifically seems to be the problem when naively trying to load sass.js using CommonJS. I suspect that web workers are not necessary since it would be perfectly acceptable to run in sync mode.

I understand that you guys worked a NodeJS module. I believe that the conditions should be largely similar. I assume that Node also wants to run without Web Workers. Any information on what you may had to tweak for Node would be helpful.

**Comment by rodneyrehm** [comment]
> Looking at their project, they are using this file: https://github.com/yogthos/lein-sass/blob/master/resources/sass.min.js. Is this a modified version of the script?

I don't know, maybe @yogthos can answer that? But it looks like they're using an older version (libsass 3.1), the current version ships libsass 3.2.5

> Any information on what you may had to tweak for Node would be helpful.

Nothing had to be tweaked to [run on Node](https://github.com/medialize/sass.js#synchronous-api-nodejs). You're right that Node does not support the Worker API and has to use `sass.sync.js`.

> Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot call method "slice" of null (file:/Users/fredfortier/Code/kwcn-post-13/kwcn-business-logic/src/test/resources/modules/sass/sass.sync.js#76)

That line is emscripten's preamble. Without more context (which slice call), I'm afraid I have no idea what the problem might be. Is there a way to properly debug that code? Or can you add some `console.logs()` to find out where things are derailing? My gut says that the environment likely provides a variable that Node knows (e.g. `process`) but not with the same structure Node does (e.g. missing `process.argv`) - and that's why things blow up.

Is there an easy/quick way for me to get a Rhino or Nashorn instance running to experiment?

**Comment by fredfortier** [comment]
I am happy to set one up for you as it would be really nice to get this
work.

I can setup an EC2 instance for you with a small Java test project which
you can build and run using single commands. That way you will be able to
replicate the error and modify things as needed. Would that work for you?
Let me know if you would like anything else to make this easy for you.

On Wednesday, September 2, 2015, Rodney Rehm <notifications@github.com>
wrote:

> Looking at their project, they are using this file:
> https://github.com/yogthos/lein-sass/blob/master/resources/sass.min.js.
> Is this a modified version of the script?
>
> I don't know, maybe @yogthos <https://github.com/yogthos> can answer
> that? But it looks like they're using an older version (libsass 3.1), the
> current version ships libsass 3.2.5
>
> Any information on what you may had to tweak for Node would be helpful.
>
> Nothing had to be tweaked to run on Node
> <https://github.com/medialize/sass.js#synchronous-api-nodejs>. You're
> right that Node does not support the Worker API and has to use
> sass.sync.js.
>
> Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot call method
> "slice" of null
> (file:/Users/fredfortier/Code/kwcn-post-13/kwcn-business-logic/src/test/resources/modules/sass/sass.sync.js#76)
>
> That line is emscripten's preamble. Without more context (which slice
> call), I'm afraid I have no idea what the problem might be. Is there a way
> to properly debug that code? Or can you add some console.logs() to find
> out where things are derailing? My gut says that the environment likely
> provides a variable that Node knows (e.g. process) but not with the same
> structure Node does (e.g. missing process.argv) - and that's why things
> blow up.
>
> Is there an easy/quick way for me to get a Rhino or Nashorn instance
> running to experiment?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/medialize/sass.js/issues/36#issuecomment-137139047>.
>


-- 
Frédéric Fortier

Check out my professional profile and connect with me on LinkedIn.
http://lnkd.in/aM86Kf

**Comment by rodneyrehm** [comment]
> I can setup an EC2 instance for you with a small Java test project …

or you just throw the relevant classes / project into a gist and I'll run that stuff locally ;)

**Comment by fredfortier** [comment]
Even better! I will do that and send you the link when it is ready.

**Comment by fredfortier** [comment]
I have created a gist for Rhino: https://gist.github.com/fredfortier/7cb24fd1fb58271758c7

**Comment by rodneyrehm** [comment]
After having quite the fun with mvn I finally figured out that Rhino is considered the shell environment (because it's not web, not worker and not node) and then fails because of not knowing `print`.

I did not get the same error you did:

```
Exception in thread "main" java.lang.RuntimeException: could not run script
	at TestRhino.main(TestRhino.java:30)
Caused by: org.mozilla.javascript.EcmaError: ReferenceError: "print" is not defined. (sass/sass.sync.js#133)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3951)
	…
```

that said, It looks like you may be experiencing kripken/emscripten#2601. according to [how to work around node.js dependencies?](http://stackoverflow.com/questions/24821994/how-to-work-around-node-js-dependencies) "simply using Nashorn instead would just work".

I'm not able to pour any more time into this tonight. I'm not a Java guy. I've tried a [Nashorn tutorial](http://winterbe.com/posts/2014/04/05/java8-nashorn-tutorial/) and stopped when realizing I needed soemthing like [jvm-npm](http://stackoverflow.com/questions/19500141/how-can-i-use-commonjs-modules-with-oracles-new-nashorn-js-engine) to make `require()` work.

Is there a reason you went with Rhino? Do you mind trying out Nashorn?

**Comment by fredfortier** [comment]
Thanks for trying! Sorry you had to wrestle with Maven.

I just now notice that the error is about "print". It was something else yesterday. It is possible to inject "print" in the scope and map to Java system output function. I will try that to see if it moves any further.

The main reason that I went with Rhino is that I need this to work with Java 6/7. Nashorn is bundled with Java 8. That said, it might be possible to use a separately packaged Nashorn lib on earlier platform but could not find obvious ways to do that.

I will add another test case for Nashorn so we at least know if it works.

**Comment by fredfortier** [comment]
Got right past the print error but back to yesterday's error.

requiring sass.sync.js...
Exception in thread "main" java.lang.RuntimeException: could not run script
	at com.enchoice.kwcn.TestRhino.main(TestRhino.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot call method "slice" of null (sass-compiler/target/classes/modules/sass/sass.sync.js#76)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3951)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3929)
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3962)

**Comment by rodneyrehm** [comment]
@fredfortier have you made any progress? could you resolve your issue?

**Comment by fredfortier** [comment]
Hi @rodneyrehm - Sorry for not getting back to you earlier. I got caught up in some other things. I did not try Nashorn yet. I will shortly. Based on the fact that other projects seemed to have used it, it is most likely going to work. However, I would need it to work in Rhino to be any useful. Is there any "tweak" that could circumvent this "emscripten" error?

Btw - my current solution is to use JRuby which allows me to compile with the Ruby SASS compiler. This presents it's own challenge. JRuby is a very large library and seems prone to environment compatibility issues. It would be much cleaner to compile using JavaScript.

**Comment by rodneyrehm** [comment]
> Based on the fact that other projects seemed to have used it, it is most likely going to work.

If you get it working, I'd like to add your findings to the wiki page - unless, even better, you can make the Nashorn bundle open source, so that I can simply link to it. Apparently there is a need for running SCSS in Java, without using JNI (or whatever, I'm not a Java developer) to interface with the C++ library directly.

> However, I would need it to work in Rhino to be any useful. Is there any "tweak" that could circumvent this "emscripten" error?

That's unfortunate. I'm not aware of any significant changes that would solve your problem. You'd have to take a look at kripken/emscripten#2601 or possibly open a new issue. I assume the problem is somewhere in [shell.js](https://github.com/kripken/emscripten/blob/master/src/shell.js), because that's where the environment is classified (and Rhino is identified as "shell").

I have already prepared the changes for [libsass 3.3](https://github.com/medialize/sass.js/tree/feature/libsass-3.3) which you could try compiling using the latest emscripten version (1.34.9, from last week). But I wouldn't get my hopes up.

> Btw - my current solution is to use JRuby which allows me to compile with the Ruby SASS compiler.

As far as I understood, the Ruby version is supposed to switch to using libsass as soon as it has caught up with the feature-set. Once/if that happens, the Ruby solution might be facing some new problems.

**Comment by rodneyrehm** [comment]
@fredfortier maybe https://github.com/kripken/emscripten/issues/3821#issuecomment-143436330 helps you track things down with Rhino.

**Comment by m4r71n** [comment]
Today I tried to get sass.js running on Rhino (1.7.7.1) and Nashorn (jdk8u72).
I did not manage to get sass.js running on Rhino because of an error I don't know how to solve:
```
Exception in thread "main" org.mozilla.javascript.JavaScriptException: abort("Assertion failed: Typed arrays 2 must be run on a little-endian system") at (no stack trace available)
Assertion failed: Typed arrays 2 must be run on a little-endian system
Assertion failed: Typed arrays 2 must be run on a little-endian system
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information. (sass.sync.js#97)
```
**But I did manage to get sass.js running on Nashorn**. Sometimes I'll get the following output on stdout but it will work anyway:
```TypeError: Cannot read property "_ready" from undefined```
This seems to be related with `Sass._ready` and the `setInterval` shim I've used for Nashorn. I'll have to investage on this.

I've created a demo repo: https://github.com/m4r71n/sass.js-rhino-nashor

**Comment by rodneyrehm** [comment]
@m4r71n nice! I see you're already using the latest version of sass.js (0.9.6). We've dropped the separate memory file in 0.9.5 but did not clean up the `Module.onRuntimeInitialized()` afterwards - as things were still working fine. I've removed the obsolete things and created a version for you to re-test your Nashorn demo in the branch [cleanup-initialization](https://github.com/medialize/sass.js/tree/cleanup-initialization) (including dist files).

As for the Rhino problem I'm not sure what's going on. The assertion is made in [preamble.js](https://github.com/kripken/emscripten/blob/42fb486c53d627b203b77af6e5d0c088c0ad03ad/src/preamble.js#L1532) and some background can be found in kripken/emscripten#3951. I'm not sure why this assertion is failing for your Rhino test, but not for your Nashorn test on the same machine. Maybe @kripken has an idea? In the meantime I've prepared the branch [test-safe-split-memory](https://github.com/medialize/sass.js/tree/test-safe-split-memory) in which that assertion is disabled (including dist files) so you can have a look if sass.js works for you in Rhino anyway. Ally my local tests are passing - but apparently I'm running things on a little-endian system anyway, so what do I know…

**Comment by kripken** [comment]
That assertion failing suggests either typed arrays are big-endian, or typed arrays are not fully functional. Perhaps Rhino's typed array support is limited?

**Comment by m4r71n** [comment]
@rodneyrehm Thx for [cleanup-initialization](https://github.com/medialize/sass.js/tree/cleanup-initialization). `TypeError: Cannot read property "_ready" from undefined` does not appear anymore with Nashorn.

With [test-safe-split-memory](https://github.com/medialize/sass.js/tree/test-safe-split-memory) on Rhino I now get another error:
```
Exception in thread "main" org.mozilla.javascript.JavaScriptException: abort(7) at (no stack trace available)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information. (test-safe-split-memory_sass.sync.js#7326)
```
I've pretty printed `test-safe-split-memory_sass.sync.js` before and I've updated my repo see [test-safe-split-memory_sass.sync.js](https://raw.githubusercontent.com/m4r71n/sass.js-rhino-nashorn/master/resources/test-safe-split-memory_sass.sync.js). Line 7321-7329 are:
```
7321:		function invoke_vii(index, a1, a2) {
7322:			try {
7323:				Module["dynCall_vii"](index, a1, a2)
7324:			} catch (e) {
7325:				if (typeof e !== "number" && e !== "longjmp")
7326:					throw e;
7327:				asm["setThrew"](1, 0)
7328:			}
7329:		}
```

@gbrail I saw that you've checked in typed array support for Rhino. Do you have an idea why the [assertion](https://github.com/kripken/emscripten/blob/42fb486c53d627b203b77af6e5d0c088c0ad03ad/src/preamble.js#L1532) in emscripten is failing with Rhino?

**Comment by gbrail** [comment]
Like a lot of Java code, Rhino writes byte arrays big-endian. The assertion
in that file seems to be checking to ensure that the byte array is
little-endian.

On Wed, Feb 3, 2016 at 12:31 AM, Martin Lepadusch <notifications@github.com>
wrote:

> @rodneyrehm <https://github.com/rodneyrehm> Thx for cleanup-initialization
> <https://github.com/medialize/sass.js/tree/cleanup-initialization>. TypeError:
> Cannot read property "_ready" from undefined does not appear anymore with
> Nashorn.
>
> With test-safe-split-memory
> <https://github.com/medialize/sass.js/tree/test-safe-split-memory> on
> Rhino I now get another error:
>
> Exception in thread "main" org.mozilla.javascript.JavaScriptException: abort(7) at (no stack trace available)
> If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information. (test-safe-split-memory_sass.sync.js#7326)
>
> I've pretty printed test-safe-split-memory_sass.sync.js before and I've
> updated my repo see test-safe-split-memory_sass.sync.js
> <https://raw.githubusercontent.com/m4r71n/sass.js-rhino-nashorn/master/resources/test-safe-split-memory_sass.sync.js>.
> Line 7321-7329 are:
>
> 7321:       function invoke_vii(index, a1, a2) {
> 7322:           try {
> 7323:               Module["dynCall_vii"](index, a1, a2)
> 7324:           } catch (e) {
> 7325:               if (typeof e !== "number" && e !== "longjmp")
> 7326:                   throw e;
> 7327:               asm["setThrew"](1, 0)
> 7328:           }
> 7329:       }
>
> @gbrail <https://github.com/gbrail> I saw that you've checked in typed
> array support for Rhino. Do you have an idea why the assertion
> <https://github.com/kripken/emscripten/blob/42fb486c53d627b203b77af6e5d0c088c0ad03ad/src/preamble.js#L1532>
> in emscripten is failing with Rhino?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/medialize/sass.js/issues/36#issuecomment-179087705>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>

**Comment by rodneyrehm** [comment]
In other words emscripten won't run on Rhino, period?

**Comment by m4r71n** [comment]
@gbrail Thank you very much for your comment! I'm not sure if you got another notification so I'll reask the [question](https://github.com/medialize/sass.js/issues/36#issuecomment-179408686) from @rodneyrehm:
`In other words emscripten won't run on Rhino, period?`

**Comment by gbrail** [comment]
I don't know why enscripten has a dependency on the byte order. Perhaps
someone from that project can help us understand. Until then it won't work
unless either they change something or we add a Rhono feature to select the
byte order.

On Thursday, February 4, 2016, Martin Lepadusch <notifications@github.com>
wrote:

> @gbrail <https://github.com/gbrail> Thank you very much for your comment!
> I'm not sure if you got another notification so I'll reask the question
> <https://github.com/medialize/sass.js/issues/36#issuecomment-179408686>
> from @rodneyrehm <https://github.com/rodneyrehm>:
> In other words emscripten won't run on Rhino, period?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/medialize/sass.js/issues/36#issuecomment-179917778>.
>


-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>

**Comment by rodneyrehm** [comment]
I've just released [0.9.7](https://github.com/medialize/sass.js/releases/tag/0.9.7) containing the fix you needed for Nashorn. I'm going to declare sass.js incompatible with Rhino for now.

@m4r71n If you publish a proper Sass.js + Nashorn package somewhere, please send me the link :)

**Comment by kripken** [comment]
> I don't know why enscripten has a dependency on the byte order. Perhaps someone from that project can help us understand. 

1. JavaScript typed arrays use the underlying system endianness. On a little-endian machine, they are little-endian, etc. This was decided upon back in the day for performance, I assume.
2. Emscripten uses typed arrays to represent memory, for speed.
3. C and C++ code can depend on endianness, and the LLVM optimizer assumes endianness and relies upon it. Therefore the code emscripten emits will often not work if the endianness is not what LLVM assumed.

**Comment by gbrail** [comment]
I know very little of sass.js and emscripten so sorry if I'm still missing
some context.

The assumption that we made with typed arrays in Rhino is that the JVM is
the "machine" and most Java-based software I've worked on assumes that it
is big-endian. (Java came from Sun...) So I decided to treat the JVM as
big-endian on all platforms like much of the Java software I've seen
before. I thought that was best in keeping with the Java philosophy that
the JVM hides the programmer from the hardware, and it allows Rhino
programs to interoperate regardless of hardware as long as they are all on
the JVM.

So is emscripten / sass.js trying to emulate the byte order of the "CPU"?
If that's the case then I think that supporting big-endian byte order on
Rhino, which relies on the JVM abstraction, makes sense, and I'd argue that
it should support both "endiannesses."

Or is emscripten / sass.js somehow trying to exhange data with native code
that has a variable byte order?

If that's the case then we can look at enhancing Rhino to make it possible
to select the byte order for typed arrays, the way that Node.js does in its
"Buffer" class.

On Thu, Feb 4, 2016 at 12:26 PM, Alon Zakai <notifications@github.com>
wrote:

> I don't know why enscripten has a dependency on the byte order. Perhaps
> someone from that project can help us understand.
>
>
>    1. JavaScript typed arrays use the underlying system endianness. On a
>    little-endian machine, they are little-endian, etc. This was decided upon
>    back in the day for performance, I assume.
>    2. Emscripten uses typed arrays to represent memory, for speed.
>    3. C and C++ code can depend on endianness, and the LLVM optimizer
>    assumes endianness and relies upon it. Therefore the code emscripten emits
>    will often not work if the endianness is not what LLVM assumed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/medialize/sass.js/issues/36#issuecomment-180032175>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>

**Comment by kripken** [comment]
Emscripten assumes what the typed array spec says, which is that typed arrays have the endianness of the underlying CPU. As mentioned earlier, I suspect this decision was made for performance reasons back in the day. Sounds like Rhino has a different approach here, of a standard endianness regardless of the underlying CPU. I agree that's much more portable :)

In any case, the two are not compatible - as a result that almost all CPUs are little-endian, emscripten's LLVM target is defined as litle-endian. And LLVM bakes that into the code, so the generated programs rely on little endianness. Emscripten-compiled programs need little-endian typed arrays.

**Comment by gbrail** [comment]
OK, that makes sense.

Rhino development is a little slow now but I get time now and then and so
do a few others. We'll see what we can do about making this configurable.

On Fri, Feb 5, 2016 at 12:33 PM, Alon Zakai <notifications@github.com>
wrote:

> Emscripten assumes what the typed array spec says, which is that typed
> arrays have the endianness of the underlying CPU. As mentioned earlier, I
> suspect this decision was made for performance reasons back in the day.
> Sounds like Rhino has a different approach here, of a standard endianness
> regardless of the underlying CPU. I agree that's much more portable :)
>
> In any case, the two are not compatible - as a result that almost all CPUs
> are little-endian, emscripten's LLVM target is defined as litle-endian. And
> LLVM bakes that into the code, so the generated programs rely on little
> endianness. Emscripten-compiled programs need little-endian typed arrays.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/medialize/sass.js/issues/36#issuecomment-180545928>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>

**Comment by m4r71n** [comment]
@kripken Thx for your clarification.
@gbrail Thx for your consideration. I wanted to ask if I should file an issue on the Rhino-Repo but I saw that you already did that: https://github.com/mozilla/rhino/issues/265
